### ISSUE TITLE
How to integrate ansible-lint-rules with ansible-lint?

### ISSUE THREAD

**Issue by bbaassssiiee** [tsukinowasha/ansible-lint-rules#3]
Is it possible to merge the rules-sets, yours and the original? Either at install time, or by pull-request.

**Comment by shirou** [comment]
You can specify multiple rule sets by using `-r` option. Or, we can merge (a part of ) your rules into this repository if you send PR.

**Comment by bbaassssiiee** [comment]
ansible-lint has a couple of rules, these are separate. When I wanted to use it with http://pre-commit.com it turned out that integration is not so simple.

**Comment by aioue** [comment]
I use https://github.com/willthames/ansible-lint daily but would like to have the extra rules in this project as well - have you considered merging the projects?
